version: "3.8"
services:
  api:
    container_name: api
    # build: docker/api/
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    ports:
      - 8080:8080
    links:
      - mysql
    tty:
      true
    volumes:
      - ./todo:/go/src/api

  mysql:
    container_name: mysql
    build: ./docker/database/
    hostname: mysql
    ports:
      - "3306:3306"