version: "3.8"
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    ports:
      - 8080:8080
    links:
      - mysql
    volumes:
      - ./api:/go/src/api

  mysql:
    container_name: mysql
    build: ./docker/database/
    hostname: mysql
    environment:
      BIND-ADDRESS: 0.0.0.0
    ports:
      - "3306:3306"