// Code generated by SQLBoiler 4.2.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Book     string
	Branch   string
	Division string
	User     string
}{
	Book:     "book",
	Branch:   "branch",
	Division: "division",
	User:     "user",
}
